### ISSUE TITLE
User-mention links are broken

### ISSUE THREAD

**Issue by epoirier** [myfossil/myfossil-theme#180] opened 2015-08-11 18:20 UTC
When one user mentions another use in a post or comment it is automatically turned into a link.  However, the link that is generated is currently broken and leads to a not-found page.

Example:

![image](https://cloud.githubusercontent.com/assets/643301/9206080/c7c85768-4033-11e5-8d96-50f06cb1d7e5.png)

Clicking \@ejpoirier leads to:

![image](https://cloud.githubusercontent.com/assets/643301/9206111/e287037e-4033-11e5-9874-fc61b85ce552.png)

It appears this is because the mention-link is malformed.  Here's what the link looks like:

`http://myfossil.staging.wpengine.com/members/epoirier-test/%3Ca%20href=%22http:/myfossil.staging.wpengine.com/members/epoirier/%22%20rel=%22nofollow%22%3Ehttp:/myfossil.staging.wpengine.com/members/epoirier/%3C/a%3E/`

**Comment by shanebp** [comment] 2015-08-11 21:39
This is caused by a custom filter in myfossil-theme\includes\filters.php

`function filter_bp_get_activity_content_body( $content ) {
    return auto_link_text( $content );
}
add_filter( 'bp_get_activity_content_body', 'filter_bp_get_activity_content_body' );
remove_filter( 'bp_get_activity_content_body', 'make_clickable', 9 );
remove_filter( 'bp_get_activity_content_body', 'bp_activity_truncate_entry', 0 );`

If I remove the filter and remove the removing of make_clickable, iow.

`//add_filter( 'bp_get_activity_content_body', 'filter_bp_get_activity_content_body' );
//remove_filter( 'bp_get_activity_content_body', 'make_clickable', 9 );`

Then the @ mention link works and any included urls are clickable.
You can see this on staging -home page:  @epoirier – https://www.google.com

I don't know why that code was added to filters.php. 
And am unaware if removing will cause other issues.

**Comment by epoirier** [comment] 2015-08-11 22:25
@woodb Do you know the purpose of the custom filter?

**Comment by woodb** [comment] 2015-08-15 14:11
So the purpose of those hooks was to do the fossil link replacement w/ the number. In the commit that closed this one out I've put a bit more explanation on what was happening here... anyway, all fixed :)

**Comment by woodb** [comment] 2015-08-15 14:24
Dang it, this got reverted...

**Closed by woodb** 2015-08-15 14:24 UTC
Labels: bug, discussion
